---
# Basic provisioning example
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: "direktiv-key"
    aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID}}"
    aws_secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY}}"
    vpc_subnet_id: "subnet-0f1d1224e0aae88d9"
    instance_type: "t2.micro"
    security_group_id: "sg-0abcc9883f0d02f90"
    region: "ap-southeast-2"
    ami: "ami-0e812285fd54f7620"

  tasks:
  - name: Create an EC2 instance
    amazon.aws.ec2_instance:
      name: "Test-Ansible"
      key_name: "{{ key_name }}"
      aws_access_key: "{{ aws_access_key }}"
      # {{ lookup('env','AWS_ACCESS_KEY_ID') }}
      aws_secret_key: "{{ aws_secret_key }}"
      # {{ lookup('env','AWS_SECRET_ACCESS_KEY') }}
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ security_group_id  }}"
      count: 1
      wait: yes
      aws_region: "{{ region  }}"
      network:
         assign_public_ip: true
      image_id: "{{ ami }}"